PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema:      <http://schema.org/>
PREFIX dc:          <http://purl.org/dc/elements/1.1/>
PREFIX foaf:        <http://xmlns.com/foaf/0.1/>

SELECT ?person ?name ?book ?title {
  ?person dbpedia-owl:birthPlace [ rdfs:label "San Francisco"@en ].
  ?viafID schema:sameAs ?person;
               schema:name ?name.
  ?book dc:contributor [ foaf:name ?name ];
              dc:title ?title.
} LIMIT 100